# ============================================
# Booking Service — Deployment + Service
# ============================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
      - name: booking-service
        image: booking-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/booking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: booking-service-svc
  namespace: healthcare
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: booking-service
