# ============================================
# Booking Service - Kubernetes Profile
# Overrides external service URLs and DB config
# ============================================

# DataSource - MySQL (K8s service name)
spring.datasource.url=jdbc:mysql://mysql-service:3306/booking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# External Services (K8s service names)
patient.service.url=http://patient-service-svc:8080
doctor.service.url=http://doctor-service-svc:8082
